### ISSUE TITLE
Overflowing Tech Stack Bar in Developer Card for Small Screen Sizes

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#10]
On small screen sizes, the tech stack bar within the developer card is overflowing and extending beyond the boundaries of the card. This overflow issue affects the visual presentation and readability of the tech stack information. It needs to be fixed to ensure the tech stack bar remains within the card boundaries.
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/d5cfeda5-3401-4a0c-ab60-01aee1b4e456)

**Comment by rawasaditya** [comment]
@martinyis  Assign this to me I have solution and PR is [here](https://github.com/martinyis/RepoAppIdea/pull/13)

**Comment by martinyis** [comment]
> @martinyis Assign this to me I have solution and PR is [here](https://github.com/martinyis/RepoAppIdea/pull/13)

@rawasaditya Thank you very much for your contribution. But you changed the wrong card. You were supposed yo changed the developer card but you changed the project card. Next time read the task more carefully and make sure you get assigned

**Comment by Vidhanvyrs** [comment]
Hi @martinyis can you assign this issue to me I  can help
