### ISSUE TITLE
Implementation of CreateProject Page

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#11]
The CreateProject page needs to be implemented within the repository application. This page should be responsive, adapting to different screen sizes, and all input fields should be saved in a single state object. The design for the CreateProject page can be found in the following link:

[CreateProject Page Design](https://www.figma.com/file/1N2Bpuq4XmzwBs7pX99Z5U/RepoAppIdea?type=design&node-id=0%3A1&t=T2eQCnDJbzbknBEq-1)

Please refer to the provided design for visual guidance on how the CreateProject page should be structured and styled.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/5cbe29ed-1c42-4c27-8b03-db36c18265c8)

**Comment by karthickbharathi1** [comment]
Hi @martinyis , can you assign this issue to me?

**Comment by martinyis** [comment]
> Hi @martinyis , can you assign this issue to me?

@karthickbharathi1  Go ahead. Make sure you follow all instructions above
