### ISSUE TITLE
Bottom Bar Shifted to Top in UserBoard Developers Page (Specific Developers Cards)

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#16]
In the UserBoard Developers page, the bottom bar is shifted to the top in a few specific developers' cards. This issue is observed in the src/pages/UserBoard/Developers directory. The bar should be at he bottom of the card!

Screen shot below

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/cc01f60a-444c-4d4c-88c4-ea713e49f8c2)

**Comment by Shiv-2712** [comment]
Hi, I want to work on this issue.

**Comment by martinyis** [comment]
> Hi, I want to work on this issue.

@Shiv-2712 Sure, I will assign it to you go ahead!

**Comment by Shiv-2712** [comment]
Hi, I ran the application but the data doesn't loads in the Developer section.

Node.js - 16.20.0 (LTS)
Platform - Windows 11

![image](https://github.com/martinyis/RepoAppIdea/assets/74370135/61af38a3-48c5-475e-a9e1-8451ff02c729)
