### ISSUE TITLE
Improving frontend of the website

### ISSUE THREAD

**Issue by harshsbhandari** [martinyis/RepoAppIdea#17]
Hey @martinyis, can I work on improving the frontend of the website starting with the navigation bar itself?

**Comment by martinyis** [comment]
> Hey @martinyis, can I work on improving the front end of the website starting with the navigation bar itself?

@harshsbhandari Thank you for your interest. But you should have opened an issue with the exact problem and exact solution possible. Of course, you can try to improve the nav bar but I am no promising that I will merge your pr. But sure you can take a shot
