### ISSUE TITLE
Padding for Username

### ISSUE THREAD

**Issue by bharathkalyans** [martinyis/RepoAppIdea#18]
* Add padding for the username button, or limit the size of the username while validating it.
* The text is overflowing if the character exceeds 15 characters.
<img width="1440" alt="RepoIdea" src="https://github.com/martinyis/RepoAppIdea/assets/49526472/f948d9a4-d730-490a-9787-f78e6af0bd91">

**Comment by martinyis** [comment]
> @bharathkalyans I would like to work on it

Go ahead!

**Comment by harshsbhandari** [comment]
hey @martinyis, I have solved the issue but I see this when I pushed changes to the branch, can you help for the same.
![Screenshot (115)](https://github.com/martinyis/RepoAppIdea/assets/73375087/a893b05f-bd3d-493e-b59c-ad2214c3768a)

**Comment by bharathkalyans** [comment]
Looks @harshsbhandari has already solved the bug! 🙌🏼

**Comment by bharathkalyans** [comment]
* If you look at phone screen size, the `...` are leaking out.
* Though @harshsbhandari managed to limit the character size, adding padding would really increase the UI effectiveness!
* Any thoughts on this @martinyis ?? 🧐
<img width="545" alt="Screenshot 2023-06-22 at 11 04 56 PM" src="https://github.com/martinyis/RepoAppIdea/assets/49526472/02184a02-64f3-4297-be3f-9e1a4c7fbb4f">

**Comment by martinyis** [comment]
> * If you look at phone screen size, the `...` are leaking out.
> * Though @harshsbhandari managed to limit the character size, adding padding would really increase the UI effectiveness!
> * Any thoughts on this @martinyis ?? 🧐
> 
> <img alt="Screenshot 2023-06-22 at 11 04 56 PM" width="545" src="https://user-images.githubusercontent.com/49526472/248011211-02184a02-64f3-4297-be3f-9e1a4c7fbb4f.png">

@bharathkalyans You are right! Make a pr with changes, I will review.

**Comment by bharathkalyans** [comment]
@martinyis let @harshsbhandari  handle this PR! I am busy with some other stuff. Will start contributing to the project once I am done with those tasks 😀

**Comment by harshsbhandari** [comment]
@martinyis @bharathkalyans no problem
