### ISSUE TITLE
Prevent Scrolling When Burger Menu is Open

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#19]
We need to implement a feature in our GitHub project that prevents scrolling when the burger menu is open. This is essential to ensure a smooth user experience and avoid accidental clicks on unintended links. By disabling scrolling while the menu is open, we can keep the user's attention focused on the menu options and minimize the risk of navigating to unintended pages. This improvement will enhance usability and prevent any frustrations that users may encounter when interacting with the menu.
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/220e5271-e015-4c56-b173-67fb53545493)

Thank you for your interest. Make sure you leave a star and visit the website!

**Comment by yacdanyCR** [comment]
@martinyis  Assaign this to me

**Comment by martinyis** [comment]
> @martinyis Assaign this to me

@yacdanyCR  Go ahead, I assigned it to you!
