### ISSUE TITLE
Improve Scrollbar Styling for ProjectCard

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#20]
Currently, the scrollbar appearance for the ProjectCard needs improvement. We should enhance the visual aesthetics and usability of the scrollbar to provide a better user experience. By customizing the scrollbar's design and behavior, we can ensure that it aligns with the overall project's visual theme and is more visually appealing. Additionally, we should consider optimizing the scrollbar's functionality to make scrolling within the ProjectCard smoother and more intuitive. These enhancements will contribute to an enhanced user interface and an improved browsing experience for our users.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/f5e2d9d9-3414-4500-9d38-d18ae4afb72f)

**Comment by Pulkitxm** [comment]
Can I get assigned ? lemme know how to start

**Comment by martinyis** [comment]
> Can I get assigned ? lemme know how to start

@Pulkitxm Go ahead!
