### ISSUE TITLE
Sceleton for Developers page

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#22]
To improve the user experience, we need to create a new component that showcases a skeleton loading effect for the Developer Page. This new component should be located in the src/pages/UserBoard directory, along with all the necessary source files.

The skeleton loading effect should mimic the layout and structure of the actual developer content. It should consist of 5-6 Developer Cards, visually representing the developer profiles or projects that will be loaded. Instead of displaying real developer information, these cards will display a placeholder skeleton effect to indicate that the content is loading. This effect provides users with a visual cue that work is in progress, keeping them engaged during the loading process.

By implementing the skeleton loading effect in the Developer Page component, we can enhance the user experience by providing a more polished and seamless loading transition. This will ensure that users are aware that the developer content is being loaded and encourage them to wait patiently for the actual data to appear.

**Comment by asatwik218** [comment]
are you looking for somebody to work on this? If yes i would like to do so

**Comment by martinyis** [comment]
> are you looking for somebody to work on this? If yes i would like to do
@asatwik218  Go ahead, I assigned it to you!
