### ISSUE TITLE
Displaying Invalid Input Message on Signup Page While Typing

### ISSUE THREAD

**Issue by otnansirk** [martinyis/RepoAppIdea#26]
Currently, on the signup page of our application, error messages for invalid input are being displayed immediately upon opening the page. This can be confusing for users as they haven't had a chance to enter any information yet. To improve the user experience, we should modify the behavior to only show error messages when users start typing in the input fields during the signup process.

Should :
Perform validation checks on the input fields as users type, including email format validation and password criteria verification.
If an error is detected, dynamically display the appropriate error message near the respective input field.

**Comment by Pratyakshshiv** [comment]
can i work on this @martinyis ?

**Comment by Pratyakshshiv** [comment]
I have fixed this issue by checking if signup button is disabled then no error should be show and one the signup button is enabled then only errors should be visible 
but what about "You are not logged in..." error should i also remove this?
![image](https://github.com/martinyis/RepoAppIdea/assets/69101089/74006447-4b62-4855-bb44-94c4f8cda57f)

**Comment by martinyis** [comment]
> I have fixed this issue by checking if signup button is disabled then no error should be shown and once the signup button is enabled then only errors should be visible but what about "You are not logged in..." error should i also remove this? Waiting for your confirmation to make PR ![image](https://user-images.githubusercontent.com/69101089/248171219-74006447-4b62-4855-bb44-94c4f8cda57f.png)

Don't worry about the login message. It is back end issue, I will take care of it later, just make a pr I will review it
