### ISSUE TITLE
Fix NavBar merge

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#28]
As you can see in the picture below, at a resolution of about 700px, the Logout/Login button is touching the Signup/User Account button. There should be some gap or padding.

![Снимок экрана 2023-06-22 122637](https://github.com/martinyis/RepoAppIdea/assets/97173732/b6fc0996-8ad0-4edd-8887-f3d2e228e5d1)

**Comment by Pratyakshshiv** [comment]
hey i would like to work on this issue and make my first open source contribution
Can you please assign this to me?

**Comment by martinyis** [comment]
> hey i would like to work on this issue and make my first open source contribution Can you please assign this to me?

@Pratyakshshiv That is very exciting. Go ahead!

**Comment by Pratyakshshiv** [comment]
thanks can you please tell me what should be the expected behaviour can i login button in center of developers and signup or i should shift all buttons to a little bit to the left and make equal spacing?

**Comment by Pratyakshshiv** [comment]
just asking like my solution was ok and you accepted my submission right?
sorry for asking this it's my first contribution so don't know much about this
