### ISSUE TITLE
Imrpove burger menu open/close buttons.

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#29]
Currently, when toggling the burger menu, there are two React icons that change depending on the state of the menu. The close icon is shifted slightly to the left, about 1-2 pixels. We need to implement a new mechanism that includes an animation for the burger open/close button and ensures that no elements are shifted. Use some library or whatever you want. And if it will take more then 20 lines create a new component for that button!

![Снимок экрана 2023-06-22 124156](https://github.com/martinyis/RepoAppIdea/assets/97173732/90d17fac-5018-4f0e-97c7-59bc52f00798)
![Снимок экрана 2023-06-22 124207](https://github.com/martinyis/RepoAppIdea/assets/97173732/b9632535-7115-4f3e-8e7b-b79eb7a68208)

**Comment by Kei-Ta** [comment]
I will try this issue.

**Comment by martinyis** [comment]
> I will try this issue.

Go ahead!

**Comment by Kei-Ta** [comment]
I reed the code.
I think that <HiBars3/> and <IoIosClose/> should be the same size 30.
How about you?

![image](https://github.com/martinyis/RepoAppIdea/assets/53590732/63eff178-83e3-4324-9cfe-6949a5c91ea4)
![image](https://github.com/martinyis/RepoAppIdea/assets/53590732/74914800-2095-4a0c-8637-773fbadf1723)


```
      {!navOpen ? (
        <HiBars3
          size={30}
          color="white"
          className="block md:hidden z-10 mr-4"
          onClick={toggleNav}
        />
      ) : (
        <IoIosClose
          size={40}
          color="white"
          className="block md:hidden z-10 mr-4"
          onClick={toggleNav}
        />
      )}
```

**Comment by martinyis** [comment]
> I reed the code. I think that HiBars3 component and IoIosClose component should be the same size 30. How about you?
> 
> ![image](https://user-images.githubusercontent.com/53590732/248600549-63eff178-83e3-4324-9cfe-6949a5c91ea4.png) ![image](https://user-images.githubusercontent.com/53590732/248600589-74914800-2095-4a0c-8637-773fbadf1723.png)
> 
> ```
>       {!navOpen ? (
>         <HiBars3
>           size={30}
>           color="white"
>           className="block md:hidden z-10 mr-4"
>           onClick={toggleNav}
>         />
>       ) : (
>         <IoIosClose
>           size={30} //<-this
>           color="white"
>           className="block md:hidden z-10 mr-4"
>           onClick={toggleNav}
>         />
>       )}
> ```

@Kei-Ta You are right, but if you read the issue more carefully, it says we need the new functionality with animation:)

**Comment by Kei-Ta** [comment]
I understood.
But Why did you close this issue?
I fixed icon size and merge request.
Please merge.
