### ISSUE TITLE
Hide content under burger menu

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#30]
When the burger menu is open on certain pages, you can still see content underneath it. The expected result is that when the burger menu is opened, all other content should be hidden until the user closes the menu or clicks on a link to another page.

[image](https://github.com/martinyis/RepoAppIdea/assets/97173732/c45fc2ab-a30d-4524-bcfd-850c73559e93)

**Comment by Pratyakshshiv** [comment]
i was looking through file base but i couldn't figure out why it is working fine for about section and not for others can you please tell something about it.
