### ISSUE TITLE
EASY! Change text style for Login/Logout btn

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#32]
Change the text styling for Login/Logout to match the appearance of items in the navbar, thereby reducing the stark contrast.
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/cc8ee5d9-0f23-41e5-92be-5319a4856138)

**Comment by Pratyakshshiv** [comment]
i would like to work on this

**Comment by Pratyakshshiv** [comment]
I made login/logout text to be xl for lg and md screens is this ok?
![image](https://github.com/martinyis/RepoAppIdea/assets/69101089/557d53fa-8da3-4407-911e-5735b52f54fa)

**Comment by martinyis** [comment]
> I made login/logout text to be xl for lg and md screens is this ok? Waiting for your confirmation to make PR ![image](https://user-images.githubusercontent.com/69101089/248214656-557d53fa-8da3-4407-911e-5735b52f54fa.png)

I should have just copied styles from the nav bar to these buttons. And make sure logout button has the same styles

**Comment by Pratyakshshiv** [comment]
> 

Ok the only style missing in login/logout buttons  buttons was text-xl but for small screen you already did sm:text-lg so for lg and md i did text-xl so that nothing changes for sm:

**Comment by Pratyakshshiv** [comment]
i am raising a pr so can you please review it and if anything needs to change just let me know.

**Comment by martinyis** [comment]
> > 
> 
> Ok the only style missing in login/logout buttons buttons was text-xl but for small screen you already did sm:text-lg so for lg and md i did text-xl so that nothing changes for sm: can you please tell me is that ok or anything needs to change

Make a pr I will take a look

**Comment by Pratyakshshiv** [comment]
> > > 
> > 
> > 
> > Ok the only style missing in login/logout buttons buttons was text-xl but for small screen you already did sm:text-lg so for lg and md i did text-xl so that nothing changes for sm: can you please tell me is that ok or anything needs to change
> 
> Make a pr I will take a look

found a shorter way to fix creating a pr
