### ISSUE TITLE
Fix Scrollbar 

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#37]
Scrollbar in Project Card is locked and does not work. This should be fixed ASAP! Ask any questions if needed.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/020b518f-1030-4bc2-97c8-8355f51e494a)

**Comment by KarthikShetty5** [comment]
Can u assign me this , I can fix it

**Comment by Pulkitxm** [comment]
Can I get assigned ? I Had worked on this project earlier as well So I am familiar with it's code !

**Comment by bharathkalyans** [comment]
@martinyis I am not facing issues! The scroll is working perfectly fine 🧐.

https://github.com/martinyis/RepoAppIdea/assets/49526472/cde55af9-db96-4c8b-84e1-d7d3780431a3

**Comment by martinyis** [comment]
> bharathkalyans

@bharathkalyans yeah I fixed that the same time as I made this issue. Thanks for mentioning tho

**Comment by bharathkalyans** [comment]
Cool then 🫡
