### ISSUE TITLE
Implementing Login Page UI from Figma Template

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#4]
We have a GitHub project that requires the implementation of a login page UI based on a provided Figma template. The login component is already prepared in src/pages/Login/Login.jsx. The task is to match the UI design from the Figma template and ensure it is responsive across different devices. The Figma template can be accessed at [Login Page Design](https://www.figma.com/file/1N2Bpuq4XmzwBs7pX99Z5U/RepoAppIdea?type=design&node-id=1%3A4&t=Sgu5nFqC2EchDfOu-1).

Key Requirements:

Implement the login page UI according to the provided Figma design.
Ensure responsiveness for different screen sizes.
Please let me know if you need any further details or clarification.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/ce4481fd-5960-4ca4-9c9f-b4844e5d166d)

**Comment by Nitinnangnurkar** [comment]
i am intrested to contribute on this project . font sizes for mobile view and desktop need to be same or diffrent ?

**Comment by martinyis** [comment]
> i am intrested to contribute on this project . font sizes for mobile view and desktop need to be same or diffrent ?

Hey, thank you for your interest. This issue is already done. Take a look at other issues!
