### ISSUE TITLE
Fix size of ProjectCard on Account page

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#40]
To ensure consistency and responsiveness, the Project Card on the Account page should occupy a similar amount of space as it does on the Projects page. Please exercise caution when modifying the card since changes made to it will affect all pages throughout the website. The Project Card islocated component in src/components/ProjectGallery. So most likely to solve this problem you will to fix something in **``src/pages/Account** but I am not sure about that!
![Снимок экрана 2023-06-26 133714](https://github.com/martinyis/RepoAppIdea/assets/97173732/bbc5dad6-d6bd-44eb-975e-d2062dd6229d)

**Comment by MJAlaeddini** [comment]
Hello, I want to work on this problem

**Comment by martinyis** [comment]
@MJAlaeddini Sure, go ahead!

**Comment by MJAlaeddini** [comment]
I tried to double the size of each ProjectCard on the account page as you requested. #51
