### ISSUE TITLE
Add spinner to Login, SignUp pages

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#41]
It is necessary to implement a loading spinner on the login and signup buttons of the Login and Signup pages. This spinner should appear after the user clicks on the login or signup button and remain visible until a response is received from the server. Once the response is received and the user is redirected to the home page, the loading spinner should disappear.
Note: Spinner is already implemented in **`src/components/ui`**

**Comment by Pratyakshshiv** [comment]
i added this spinner here 
when request is processing then in place of login/signup spinner will appear inside button
is that ok?
![image](https://github.com/martinyis/RepoAppIdea/assets/69101089/3693304c-1b71-4037-98d0-33f5de860c90)
