### ISSUE TITLE
 Implementing Sign Up Page UI from Figma Template

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#5]
We have a GitHub project that requires the implementation of a sign-up page UI based on a provided Figma template. The sign-up component is already prepared in src/pages/SignUp/SignUp.jsx. The task is to match the UI design from the Figma template and ensure it is responsive across different devices. The Figma template can be accessed at [Sign Up Page Design](https://www.figma.com/file/1N2Bpuq4XmzwBs7pX99Z5U/RepoAppIdea?type=design&node-id=3%3A4&t=Sgu5nFqC2EchDfOu-1).

Key Requirements:

Implement the sign-up page UI according to the provided Figma design.
Ensure responsiveness for different screen sizes.
Please let me know if you need any further details or clarification.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/04a27d40-a4bb-4ede-a851-789081b98e9e)

**Comment by EidanGar** [comment]
Hello, I would like to claim this issue. Question though, do you know somewhere I can separately run my react tailwind code? I forked the application and tried running it locally but it failed due to some errors. I have a draft for the sign up page but no way to see it.

**Comment by martinyis** [comment]
> @martinyis Hello, I would like to claim this issue. Question though, do you know somewhere I can separately run my react tailwind code? I forked the application and tried running it locally but it failed due to some errors. I have a draft for the sign up page but no way to see it.

@EidanGar  Thank you for your time and interest in this project. Unfortunately I already implemented this page so there is no need to take this issue. For the future make sure you get assigned and then tackle the issue. Take a look at other issues, you might find something interesting. Make sure you read README file to understand the whole procedure fo setting up a local environment for working on the issues!

**Comment by EidanGar** [comment]
@martinyis No problem, I got the practice I wanted. Here's the draft regardless, if you want to implement a part of it: 
```import ReactDOM from "react-dom";
import "./styles.scss";
import React, { useEffect, useState } from "react";
// import { useDispatch } form "react-redux";
// import { Link } from "react-router-dom";

const SignUp = () => {
  // const dispatch = useDispatch();
  const [user, setUser] = useState({
    username: "",
    email: "",
    password: ""
  });

  useEffect(() => {
    document.body.style.backgroundColor = "#F5F5F5";
    // Clean up the effect
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, []);

  const signUp = (e) => {
    e.preventDefault();
    // dispatch({ type: "USER", payload: user })
  };

  const signUpInputChange = (e) => {
    const { placeholder, value } = e.target;
    setUser((prev) => ({ ...prev, [placeholder.toLowerCase()]: value }));
  };

  const formInputClass =
    "placeholder:text-[#ADB5BD] p-3 outline-none rounded-lg border-[1px] border-[#CED4DA]";
  const backgroundColor = {
    background:
      "linear-gradient(180deg, rgba(39,55,77,1) 34.8538%, rgba(221,230,237,1) 34.8538%, rgba(221,230,237,1) 100%) no-repeat"
  };

  return (
    <div
      style={backgroundColor}
      className="min-h-screen text-xs leading-4 flex items-center justify-center"
    >
      <form
        onSubmit={signUp}
        className="ms:max-w-[474px] w-full h-full sm:h-fit flex flex-col items-center gap-12 px-[46px] pt-8 pb-[50px] rounded-[24px] bg-white"
      >
        <h2 className="font-semibold text-[#344767]">
          Sign up for your account
        </h2>
        <input
          onChange={signUpInputChange}
          placeholder="Username"
          type="text"
          className={formInputClass}
        />
        <input
          onChange={signUpInputChange}
          placeholder="Email"
          type="email"
          className={formInputClass}
        />
        <input
          onChange={signUpInputChange}
          placeholder="password"
          type="password"
          className={formInputClass}
        />
        <button className="p-3 outline-none bg-[#343A40] text-white rounded-lg font-semibold">
          Sign Up
        </button>
        <h3 className="text-black">
          Already have an account?&nbsp;
          <span className="font-bold cursor-pointer">Log In</span>
        </h3>
      </form>
    </div>
  );
};

export default SignUp;

const rootElement = document.getElementById("root");
ReactDOM.render(<SignUp />, rootElement);
```
