### ISSUE TITLE
Fix the size of developer cards

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#54]
Currently, on the developers' board, we have multiple developers with varying heights due to different descriptions. We need to adjust the description height to incorporate a beautiful scrollbar, ensuring that all cards have the same height. This will provide a consistent and visually appealing layout.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/89975b19-f59d-4b67-a3ab-4ac957b79de1)

**Comment by aishwarya-mali** [comment]
@martinyis I'd like to work on this issue.

**Comment by martinyis** [comment]
Assigning in order:)
