### ISSUE TITLE
Improve design of 

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#55]
We are in need of enhancing the design of ErrorPopUp.jsx, as it currently appears unattractive and requires a better overall design. This error popup is visible when creating a project and failing to provide any information in the form. form

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/31ce7fc7-b0a8-4207-a83e-ce11331a7e26)

**Comment by web-dev-kushal** [comment]
Hello I would like to work on this.. Please do assign me

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start

**Comment by martinyis** [comment]
Assigning in order:)

**Comment by waibiaf2** [comment]
I would like to help, please assign me this
