### ISSUE TITLE
Fix burger menu bug

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#56]
The burger menu currently appears below the content, but it should be positioned above the content. Additionally, the scrolling functionality should be disabled while the burger menu is in use to ensure a smooth user experience.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/2f98b187-500f-453c-b971-0a40faf32af1)
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/dd554638-b2ee-4430-85e4-355dff38098d)

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start
