### ISSUE TITLE
Add Link to footer logo

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#57]
When the logo in the footer is clicked, it should navigate to the top of the home page.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/2918baea-480f-4b44-a807-7d1b7188d09f)

**Comment by jonichi16** [comment]
Hi, can I work on this? Thanks

**Comment by martinyis** [comment]
> Hi, can I work on this? Thanks
Sure, go ahead)

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start
