### ISSUE TITLE
Fix login page err msg

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#61]
The error message that a person is not logged in should not be displayed
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/27bedc39-c13e-436c-96d7-0b118f435156)

**Comment by fiskryeziu** [comment]
This is happening because of the function in App.jsx 
```javascript
useEffect(() => {
    function start() {
      gapi.client.init({
        clientId: clientId,
        scope: '',
      })
    }
    gapi.load('client:auth2', start)
    fetchData()
  }, [])
```

**Comment by martinyis** [comment]
> This is happening because of the function in App.jsx
> 
> ```js
> useEffect(() => {
>     function start() {
>       gapi.client.init({
>         clientId: clientId,
>         scope: '',
>       })
>     }
>     gapi.load('client:auth2', start)
>     fetchData()
>   }, [])
> ```

@fiskryeziu Do you want to work on this?

**Comment by fiskryeziu** [comment]
I would be happy to work on it

**Comment by martinyis** [comment]
@fiskryeziu Go ahead!
