### ISSUE TITLE
Improve cards

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#62]
To enhance the visual appearance of the cards below, you can make the following modifications:

Decrease the text size: Reduce the font size of the text in the cards to make it smaller and more compact.
Add padding on the sides: Increase the spacing between the text and the edges of the cards by adding padding, creating some breathing space.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/4e7f7244-786a-416f-8763-7590eeb4d031)

**Comment by VhugoJc** [comment]
Can I get assigned? let me know how to start
