### ISSUE TITLE
Adjust scrollbars for developer cards

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#63]
The scrollbars on the developer cards extend beyond the borders on several screen sizes. To resolve this issue, the size of the scrollbars should be decreased.
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/e3d89a72-7e99-4df4-87df-8ae8e1627c1d)
![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/3b8fd10b-f427-498f-9ff6-1d43600c2d3f)

**Comment by theQuery** [comment]
I'd like to work on this

**Comment by martinyis** [comment]
@theQuery Go ahead!

**Comment by karenhernandeze** [comment]
Hi, can I be assigned this one?

**Comment by theQuery** [comment]
Thank you, currently in the works
