### ISSUE TITLE
Change Link for the card

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#64]
"Currently, the Project card in the project gallery has a hover effect, but when clicked, it does not perform any action. The actual link is only displayed for the repository name, but it should be displayed for the entire card. This way, when a user clicks on the card, they will be redirected to the project's repository.

**Comment by sohaibaumer** [comment]
can i get assigned?

**Comment by martinyis** [comment]
@sohaibaumer Go ahead!

**Comment by martinyis** [comment]
@sohaibaumer  If @chillerno1 wont fix bug soon I will assign it to you.
