### ISSUE TITLE
AccountEdit Page Responsiveness and Functionality

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#7]
The AccountEdit page implementation needs improvement to ensure responsiveness and functionality. Currently, the following issues are identified:

Responsive Design: The page should be optimized to work seamlessly across different devices and screen sizes. Elements should adapt and rearrange appropriately for optimal user experience.

Consolidation of Input Fields: All input fields on the AccountEdit page should be controlled within a single useState object. This will allow for efficient state management and easier synchronization of data between the input fields and the underlying component.

Save Button Functionality: The "Save" button should have its type set to "submit" to ensure proper form submission. This will enable the data entered in the input fields to be processed and saved correctly.

Cancel Button Redirection: The "Cancel" button should be configured to redirect the user to the Account page when clicked. This will provide a convenient way for users to abandon their changes and return to their account details without saving any modifications.

To resolve these issues, the AccountEdit page implementation should be revised, taking into account the mentioned requirements and recommendations for a seamless and user-friendly experience.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/f60a0a00-76f0-48d2-b40b-6f4d437db89a)

**Comment by YogeshJoshi10072000** [comment]
I can add this functionality. I am beginner in open source i have not contributed .can you assign me this project

**Comment by YogeshJoshi10072000** [comment]
after submitinng the axios is used to call backend api to update the functionality.can you give me your backend api for updating the account info.

**Comment by Pulkitxm** [comment]
Hello! I'm a beginner in open source and eager to contribute. I would love to take on the challenge of improving the responsiveness and functionality of the AccountEdit page. Could you kindly assign me this issue? Also, please provide the backend API details for updating the account information. Thank you!

**Comment by martinyis** [comment]
> Hello! I'm a beginner in open source and eager to contribute. I would love to take on the challenge of improving the responsiveness and functionality of the AccountEdit page. Could you kindly assign me this issue? Also, please provide the backend API details for updating the account information. Thank you!
Hey, thank you for your interest. You don't need API for this issue. I will be connecting API later by myself. Your task is simply to make a page and make it responsive and make sure you follow the Figma design below. And all inputs should have on state object 
https://www.figma.com/file/1N2Bpuq4XmzwBs7pX99Z5U/RepoAppIdea?type=design&node-id=0%3A1&t=T2eQCnDJbzbknBEq-1

**Comment by martinyis** [comment]
> Hello! I'm a beginner in open source and eager to contribute. I would love to take on the challenge of improving the responsiveness and functionality of the AccountEdit page. Could you kindly assign me this issue? Also, please provide the backend API details for updating the account information. Thank you!

@Pulkitxm
 Hey, thank you for your interest. You don't need API for this issue. I will be connecting API later by myself. Your task is simply to make a page and make it responsive and make sure you follow the Figma design below. And all inputs should have on state object
https://www.figma.com/file/1N2Bpuq4XmzwBs7pX99Z5U/RepoAppIdea?type=design&node-id=0%3A1&t=T2eQCnDJbzbknBEq-1

**Comment by martinyis** [comment]
> Hello! I'm a beginner in open source and eager to contribute. I would love to take on the challenge of improving the responsiveness and functionality of the AccountEdit page. Could you kindly assign me this issue? Also, please provide the backend API details for updating the account information. Thank you!

Make sure you implement AccountEdit page but not Account page

**Comment by Pulkitxm** [comment]
How can I start from here ?
https://drive.google.com/file/d/1vRAKgFduTHJQdHVb5c3D0wiZKJYF7m93

**Comment by martinyis** [comment]
@Pulkitxm  Make sure you read the README file. There are all instructions on how to set up your local environment.

**Comment by Pulkitxm** [comment]
yes I already read that , maybe an internal code issue

**Comment by martinyis** [comment]
> yes I already read that , maybe an internal code issue

@Pulkitxm  Based on your screenshot it looks like some dependencies didn't install. Make sure you have all dependencies installed. Are you working on this issue?

**Comment by Pulkitxm** [comment]
I am not able to proceed with that
