### ISSUE TITLE
Change styles for scrollbar

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#74]
The vertical scrollbar for the developer card should have the same styles as the bottom scrollbar.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/9caeaa43-990b-4fdc-9ea4-7e8b1e5c8ad0)

**Comment by theQuery** [comment]
I can fix this

**Comment by martinyis** [comment]
> Contributor

@theQuery Go ahead!

**Comment by theQuery** [comment]
Thank you
