### ISSUE TITLE
Imrpove hover effect for the button

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#76]
The current hover effect for the create button does not align well with the overall design of the website. It would be beneficial to modify the hover effect to better complement the design. Please update it according to your judgment to create a more cohesive and visually pleasing effect.

Note: You can see this button only when you logged in.

![image](https://github.com/martinyis/RepoAppIdea/assets/97173732/0e94a116-5412-4cf6-9165-6dd9d68c81a8)

**Comment by karenhernandeze** [comment]
Can I be assigned?

**Comment by martinyis** [comment]
> Can I be assigned?

@karenhernandeze  Go ahead:)
