### ISSUE TITLE
Misaligned Navbar in GitHub Repository

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#8]
The navbar in the GitHub repository is currently misaligned, appearing slightly shifted to the left. This misalignment affects the centered positioning of the "About," "Projects," and "Developers" elements within the navbar. To enhance the visual presentation and user experience, the misalignment needs to be resolved.

Please note that the requested picture cannot be directly embedded in this text-based interface. However, you can provide a link or describe the misalignment in more detail if needed.

![Снимок экрана 2023-06-15 113615](https://github.com/martinyis/RepoAppIdea/assets/97173732/ee1dbec1-60ff-4f6d-9c16-4caaf5027553)

**Comment by harshsbhandari** [comment]
Hey @martinyis, can I work on this issue.

**Comment by harshsbhandari** [comment]
Hey @martinyis, I am new to open source and by mistake I unassigned myself from this task. Can you please reassign and evaluate my PR. Thanks in advance and sorry for the trouble.
