### ISSUE TITLE
 Insufficient Width of Cards in About Section for Screens Under MD

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#9]
The cards in the About section of the webpage are not wide enough for screens smaller than the medium (MD) breakpoint. This results in cramped content or overflow, negatively affecting readability. The width of the cards needs to be adjusted to provide sufficient space for the content within them.
![Снимок экрана 2023-06-15 114208](https://github.com/martinyis/RepoAppIdea/assets/97173732/4e41cffd-4d9e-4b24-a99d-c863e066b322)

**Comment by rawasaditya** [comment]
@martinyis assign this to me I have created [PR ](https://github.com/martinyis/RepoAppIdea/pull/12) here
